version: '3.8'
services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    volumes:
      - ./server/data:/usr/src/app/data
  client:
    build: ./client
    ports:
      - "5173:5173"
